import type { OpenAPIObject } from "@nestjs/swagger";
import { ERROR_CODES } from "./error-codes";
import { ERROR_CODE_DESCRIPTIONS } from "./error-code-descriptions";

export const ERROR_TABLE_START = "{/* error-codes:start (generated by openapi:generate) */}";
export const ERROR_TABLE_END = "{/* error-codes:end */}";

/** Codes no public route declares: raised by the envelope filter or by operator-only routes. */
const FILTER_STATUS: Record<string, string> = {
  admin_api_not_configured: "503",
  bad_request: "400",
  invalid_rate_limit: "400",
  forbidden: "403",
  not_found: "404",
  unprocessable_entity: "422",
  request_failed: "4xx",
  service_unavailable: "503",
  internal_error: "500",
};

function declaredStatuses(document: OpenAPIObject): Map<string, Set<string>> {
  const found = new Map<string, Set<string>>();
  for (const item of Object.values(document.paths)) {
    for (const operation of Object.values(item as Record<string, unknown>)) {
      const responses = (operation as { responses?: Record<string, unknown> }).responses ?? {};
      for (const [status, response] of Object.entries(responses)) {
        const allOf = (response as { content?: Record<string, { schema?: { allOf?: unknown[] } }> })
          .content?.["application/json"]?.schema?.allOf;
        const enumeration = (
          allOf?.[1] as { properties?: { error?: { properties?: { code?: { enum?: string[] } } } } }
        )?.properties?.error?.properties?.code?.enum;
        for (const code of enumeration ?? []) {
          if (!found.has(code)) found.set(code, new Set());
          found.get(code)!.add(status);
        }
      }
    }
  }
  return found;
}

/** The generated block of introduction.mdx: every registered code, its statuses, its meaning. */
export function renderErrorCodeTable(document: OpenAPIObject): string {
  const statuses = declaredStatuses(document);
  const rows = ERROR_CODES.map((code) => [
    `\`${code}\``,
    [...(statuses.get(code) ?? [FILTER_STATUS[code] ?? "any"])].sort().join(", "),
    ERROR_CODE_DESCRIPTIONS[code],
  ]);
  const header = ["Code", "Status", "Meaning"];
  const widths = header.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i]!.length)));
  const line = (cells: string[]): string =>
    `| ${cells.map((c, i) => c.padEnd(widths[i]!)).join(" | ")} |`;
  return [
    ERROR_TABLE_START,
    "",
    line(header),
    `| ${widths.map((w) => "-".repeat(w)).join(" | ")} |`,
    ...rows.map(line),
    "",
    ERROR_TABLE_END,
  ].join("\n");
}

/** Replaces the marked block in an MDX page, or throws when the markers are missing. */
export function withErrorCodeTable(page: string, table: string): string {
  const start = page.indexOf(ERROR_TABLE_START);
  const end = page.indexOf(ERROR_TABLE_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error("introduction.mdx is missing the error-codes markers");
  }
  return page.slice(0, start) + table + page.slice(end + ERROR_TABLE_END.length);
}
