import type { ErrorCode } from "@lumenwipe/types";

/** What each registered code means, for the generated table in docs/api-reference/introduction.mdx. */
export const ERROR_CODE_DESCRIPTIONS: Record<ErrorCode, string> = {
  account_not_found: "The account does not exist on this network.",
  account_read_failed: "The account could not be read. Retry.",
  account_too_large: "The account has too many entries to read in one request.",
  admin_api_not_configured: "Operator key management is not configured on this server.",
  allowances_read_failed: "Token allowances could not be read. Retry.",
  api_key_not_found: "No active key with that id belongs to the caller.",
  aquarius_trustline_missing: "An Aquarius exit needs a trustline the account does not have.",
  backstop_emissions_unclaimed:
    "Blend backstop emissions must be claimed before the position can be exited.",
  backstop_token_unconvertible:
    "The Blend backstop token cannot be converted to a supported asset.",
  backstop_withdrawal_cooling_down: "A Blend backstop withdrawal is still in its cooldown.",
  backstop_withdrawal_not_queued: "A Blend backstop withdrawal must be queued first.",
  bad_request: "The request is malformed.",
  blend_emissions_trustline_missing:
    "Claiming Blend emissions needs a trustline the account does not have.",
  blend_repay_asset_balance_unknown:
    "The balance of an asset needed to repay a Blend loan could not be read.",
  blend_repay_asset_missing: "The account does not hold the asset needed to repay a Blend loan.",
  confirmation_timeout:
    "The transaction did not confirm in time. Check its status before retrying.",
  conversion_floor_missing: "A conversion carries no destination minimum.",
  conversion_provider_unrecognized: "A conversion names a provider the API does not recognize.",
  defi_exit_blocked: "A DeFi position could not be exited safely.",
  defi_exit_unsupported: "The account holds a DeFi position that cannot be exited yet.",
  defi_position_unrecognized: "A DeFi position could not be identified.",
  defi_positions_blocked: "A DeFi position blocks the close.",
  defi_positions_unavailable: "DeFi positions could not be confirmed for this account.",
  defi_positions_stale: "The detected DeFi positions are out of date. Plan again.",
  destination_not_acknowledged:
    "The destination is not a recognized exchange address and was not confirmed.",
  destination_read_failed: "The destination account could not be read. Retry.",
  fee_bump_exceeds_cap: "The sponsored fee would exceed the cap.",
  fee_bump_not_configured: "Sponsored fees are not configured on this server.",
  forbidden: "The caller is not allowed to do this.",
  forward_amount_exceeds_balance: "The mediator forward is larger than the balance being merged.",
  inner_fee_not_zero: "The inner transaction of a sponsored fee bump must carry no fee of its own.",
  integrator_api_not_configured: "Self-serve key management is not configured on this server.",
  internal_error: "Something went wrong on the server. Retry.",
  invalid_address: "The address is not a valid Stellar account.",
  invalid_addresses: "The addresses are missing or not valid Stellar accounts.",
  invalid_body: "The request body is not valid JSON or not a JSON object.",
  invalid_challenge: "The signed challenge is invalid or has expired.",
  invalid_decisions: "The decisions in the request are malformed.",
  invalid_destination: "The destination is missing or not a valid address.",
  invalid_memo: "The memo is not valid for its type.",
  invalid_network: "The network is not testnet or mainnet.",
  invalid_owner: "The owner is missing or empty.",
  invalid_rate_limit: "The rate limit override is malformed.",
  invalid_request: "The request is missing a required field.",
  invalid_signature: "The signature does not match the transaction.",
  invalid_signed_xdr: "The signed transaction is missing or cannot be decoded.",
  invalid_source: "The source is missing or not a valid address.",
  invalid_spender: "The spender is not a valid address.",
  invalid_token: "The token is not a valid contract address.",
  invalid_tokens: "The token list is malformed.",
  invalid_transaction_xdr: "The transaction is missing or cannot be decoded.",
  invalid_tx_hash: "The transaction hash is not a 64-character hex string.",
  key_limit_reached: "The wallet already has the maximum number of active keys.",
  mediator_key_misconfiguration: "The mediator key on this server is misconfigured.",
  mediator_not_configured: "The exchange (mediator) flow is not configured on this server.",
  memo_required: "The destination exchange requires a memo.",
  merge_destination_unusable:
    "The destination cannot receive the merge: it is the closing account, a LumenWipe service account, or does not exist.",
  merged_account_not_found: "The account being merged does not exist.",
  missing_parameters: "A required query parameter is missing.",
  missing_transaction: "The transaction is missing from the request.",
  needs_decisions: "The plan has decisions that are still unanswered.",
  not_found: "The route does not exist.",
  operation_not_sponsorable: "The transaction contains an operation that cannot be sponsored.",
  owner_not_found: "The owner account does not exist on this network.",
  path_lookup_failed: "The conversion path lookup failed. Retry.",
  payload_too_large: "The request body is larger than 100 KB.",
  phoenix_trustline_missing: "A Phoenix exit needs a trustline the account does not have.",
  plan_failed: "The plan could not be built. Retry.",
  provider_response_unusable:
    "The data provider returned a response that could not be used. Retry.",
  quote_drifted: "A conversion route changed between planning and building. Plan again.",
  rate_limited: "Too many requests. Wait and retry.",
  registry_expired: "The exchange registry is out of date.",
  request_failed: "The request could not be completed.",
  revoke_build_failed: "The allowance revocation could not be built. Retry.",
  revoke_needs_restore: "The allowance revocation needs ledger entries restored first.",
  revoke_simulation_failed: "The allowance revocation failed simulation.",
  revoke_unsafe: "The allowance revocation could not be built safely.",
  service_unavailable: "The service or an upstream dependency is unavailable. Retry.",
  signer_normalization_unsafe: "The account's signers cannot be normalized safely.",
  soroban_token_conversion_failed: "A Soroban token could not be converted.",
  soroban_token_conversion_unavailable: "No conversion is available for a Soroban token.",
  soroban_token_conversion_unsafe: "Converting a Soroban token is not safe.",
  soroban_token_needs_restore: "A Soroban token needs ledger entries restored first.",
  soroban_token_route_lost: "The conversion route for a Soroban token disappeared. Plan again.",
  soroban_token_transfer_failed: "A Soroban token transfer failed.",
  soroban_token_transfer_unsafe: "A Soroban token transfer is not safe.",
  soroban_token_unreadable: "A Soroban token balance could not be read.",
  soroswap_trustline_missing: "A Soroswap exit needs a trustline the account does not have.",
  source_sequence_too_far:
    "The account's sequence number is beyond what the network accepts for a merge; it cannot be closed until the ledger catches up.",
  stats_unavailable: "The stats store is unreachable. Retry.",
  submit_failed: "The transaction could not be submitted. Retry.",
  submit_rejected: "The network rejected the transaction.",
  too_many_addresses: "More addresses than a batch accepts.",
  transaction_structure_not_allowed: "The transaction is not a shape this endpoint may sign.",
  transactions_failed: "The transactions could not be built. Retry.",
  transfer_destination_missing: "A transfer carries no destination.",
  transfer_destination_unusable: "A transfer destination cannot receive its asset.",
  trustline_cannot_be_left: "A trustline cannot be left in place by the close.",
  trustline_deauthorized_with_balance:
    "A trustline holds a balance but was deauthorized by its issuer.",
  tx_not_verified: "The transaction could not be verified as a merge on the network.",
  unauthorized: "The API key, session token or operator token is missing or invalid.",
  unprocessable_entity: "The request is valid but cannot be processed.",
  unsupported_media_type: "The request body must be UTF-8 JSON.",
  unsupported_memo_type: "The memo type is not supported for this destination.",
  vault_undercollateralized: "An FxDAO vault is undercollateralized and cannot be exited.",
  withdraw_before_repay: "A loan must be repaid before the collateral can be withdrawn.",
};
