import { describe, expect, test } from "bun:test";
import { checkErrorReference } from "./check-error-reference.mjs";

const codesSource = `export const ERROR_CODES = [\n  "alpha",\n  "beta",\n] as const satisfies readonly ErrorCode[];`;
const introPage = [
  "{/* error-codes:start (generated by openapi:generate) */}",
  "| Code | Status | Meaning |",
  "| --- | --- | --- |",
  "| `alpha` | 400 | The first. |",
  "| `beta`  | 503 | The second. Retry. |",
  "{/* error-codes:end */}",
].join("\n");

function page(...rows: string[]): string {
  return ["| Code | Status | Retry | Meaning |", "| --- | --- | --- | --- |", ...rows].join("\n");
}

const alpha = "| `alpha` | 400 | After fix | The first. |";
const beta = "| `beta`  | 503 | Yes       | The second. Retry. |";

const run = (errorsPage: string): string[] =>
  checkErrorReference({ codesSource, introPage, errorsPage });

describe("check-error-reference", () => {
  test("passes when every code is listed with matching status and meaning", () => {
    expect(run(page(alpha, beta))).toEqual([]);
  });

  test("fails when the API registers a code the page does not list", () => {
    expect(run(page(alpha))).toEqual(["beta is in the API's error registry but has no row"]);
  });

  test("fails when the page lists a code the API does not register", () => {
    const extra = "| `gamma` | 400 | No | Not real. |";
    expect(run(page(alpha, beta, extra))).toEqual([
      "gamma is listed but is not in the API's error registry",
    ]);
  });

  test("fails on a duplicated code", () => {
    expect(run(page(alpha, alpha, beta))).toEqual(["alpha is listed more than once"]);
  });

  test("fails when a status or a meaning drifts from the generated table", () => {
    const wrongStatus = "| `alpha` | 422 | After fix | The first. |";
    const wrongMeaning = "| `beta` | 503 | Yes | Reworded. |";
    expect(run(page(wrongStatus, wrongMeaning))).toEqual([
      "alpha has status 422 but the generated table says 400",
      "beta has a meaning that differs from the generated table",
    ]);
  });

  test("fails on a Retry value outside the closed set", () => {
    const bad = "| `alpha` | 400 | Maybe | The first. |";
    expect(run(page(bad, beta))).toEqual([
      'alpha has Retry "Maybe"; use one of Yes, After fix, Check first, No',
    ]);
  });

  test("throws when the generated table markers are missing", () => {
    expect(() =>
      checkErrorReference({ codesSource, introPage: "no markers", errorsPage: page(alpha) })
    ).toThrow("missing the error-codes:start markers");
  });
});
