#!/usr/bin/env bash
# Re-renders every diagram from its Graphviz source and fails when a committed SVG differs.
# The generator-version comment is ignored and PNGs are not compared: both change with the
# Graphviz build, not with the diagram. Needs python3, the graphviz Python package and `dot`.
set -euo pipefail

out="docs/diagrams/output"
committed="$(mktemp -d)"
trap 'rm -rf "$committed"' EXIT

cp "$out"/*.svg "$committed"/
python3 diagrams/generator/render-all.py > /dev/null

normalize() { sed -E '/^<!-- Generated by graphviz version/d' "$1"; }

status=0
for file in "$out"/*.svg; do
  name="$(basename "$file")"
  if [ ! -e "$committed/$name" ]; then
    echo "::error file=$file::$name was produced by the generators but is not committed"
    status=1
  elif ! diff -q <(normalize "$committed/$name") <(normalize "$file") > /dev/null; then
    echo "::error file=$file::$name is stale: re-run python diagrams/generator/render-all.py and commit the output"
    status=1
  fi
done
for file in "$committed"/*.svg; do
  name="$(basename "$file")"
  if [ ! -e "$out/$name" ]; then
    echo "::error file=$out/$name::$name is committed but no generator produces it"
    status=1
  fi
done
exit "$status"
